name: Build and publish Doxygen docs

on:
  push:
    branches:
      - ci
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Doxygen
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen make graphviz

      - name: Build Doxygen documentation
        run: make docs

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/doxygen/html

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
